### PR TITLE
[REQUEST] ADD LICENSE.

### PR DESCRIPTION
**Pull request by rintim**
Please Take LICENSE of [Noname](https://github.com/libccy/noname)!

This repository is largely derived from [Noname](https://github.com/libccy/noname), which is open sourced under GPL-3, but LICENSE has been deleted from this repository. No matter what the contents of GPL-3 are, deleting LICENSE and publishing it after copying others' project code goes against the basic ethics of the open source community, not to mention the rigid requirements of GPL-3.

Please consciously take GPL-3 License , otherwise we will report this repository for [DMCA](https://www.dmca.com/).

### CODE REVIEW

**Comment by universe-st** [comment]
Agree.

**Comment by kuangshen04** [comment]
Agree.

**Comment by ansolve** [comment]
Current the repository is add LICENSE but MIT, which is incompatible with GPL-3. Besides, the owner or the maintainers baned our abilities to persuade. In this way, we consider no possibility between the repository and us to solve LICENSE problem.

**Comment by ansolve** [comment]
图片
图片

**Comment by ansolve** [comment]
图片

We underline it again to Tell: This repository is **LARGELY DERIVED** from [**Noname**](https://github.com/libccy/noname), which is open sourced under **GPL-3**, but **THE PEOPLE** of this repository **REMOVED** it.

**Pull request closed without merging**
